// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"io"
	"sync"
)

// ArchiverMock is a mock implementation of pipeline.archiver.
//
//	func TestSomethingThatUsesarchiver(t *testing.T) {
//
//		// make and configure a mocked pipeline.archiver
//		mockedarchiver := &ArchiverMock{
//			WriterFunc: func(name string) (io.WriteCloser, error) {
//				panic("mock out the Writer method")
//			},
//		}
//
//		// use mockedarchiver in code that requires pipeline.archiver
//		// and then make assertions.
//
//	}
type ArchiverMock struct {
	// WriterFunc mocks the Writer method.
	WriterFunc func(name string) (io.WriteCloser, error)

	// calls tracks calls to the methods.
	calls struct {
		// Writer holds details about calls to the Writer method.
		Writer []struct {
			// Name is the name argument value.
			Name string
		}
	}
	lockWriter sync.RWMutex
}

// Writer calls WriterFunc.
func (mock *ArchiverMock) Writer(name string) (io.WriteCloser, error) {
	if mock.WriterFunc == nil {
		panic("ArchiverMock.WriterFunc: method is nil but archiver.Writer was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockWriter.Lock()
	mock.calls.Writer = append(mock.calls.Writer, callInfo)
	mock.lockWriter.Unlock()
	return mock.WriterFunc(name)
}

// WriterCalls gets all the calls that were made to Writer.
// Check the length with:
//
//	len(mockedarchiver.WriterCalls())
func (mock *ArchiverMock) WriterCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockWriter.RLock()
	calls = mock.calls.Writer
	mock.lockWriter.RUnlock()
	return calls
}
