// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/revmux/app/executor"
)

// RunnerMock is a mock implementation of pipeline.Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked pipeline.Runner
//		mockedRunner := &RunnerMock{
//			RunFunc: func(ctx context.Context, req executor.Request, sink executor.EventSink) (executor.Result, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedRunner in code that requires pipeline.Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, req executor.Request, sink executor.EventSink) (executor.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req executor.Request
			// Sink is the sink argument value.
			Sink executor.EventSink
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *RunnerMock) Run(ctx context.Context, req executor.Request, sink executor.EventSink) (executor.Result, error) {
	if mock.RunFunc == nil {
		panic("RunnerMock.RunFunc: method is nil but Runner.Run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Req  executor.Request
		Sink executor.EventSink
	}{
		Ctx:  ctx,
		Req:  req,
		Sink: sink,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, req, sink)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedRunner.RunCalls())
func (mock *RunnerMock) RunCalls() []struct {
	Ctx  context.Context
	Req  executor.Request
	Sink executor.EventSink
} {
	var calls []struct {
		Ctx  context.Context
		Req  executor.Request
		Sink executor.EventSink
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
