// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"time"

	"github.com/umputun/revmux/app/executor"
)

// ClockMock is a mock implementation of executor.Clock.
//
//	func TestSomethingThatUsesClock(t *testing.T) {
//
//		// make and configure a mocked executor.Clock
//		mockedClock := &ClockMock{
//			AfterFuncFunc: func(d time.Duration, f func()) executor.Timer {
//				panic("mock out the AfterFunc method")
//			},
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//		}
//
//		// use mockedClock in code that requires executor.Clock
//		// and then make assertions.
//
//	}
type ClockMock struct {
	// AfterFuncFunc mocks the AfterFunc method.
	AfterFuncFunc func(d time.Duration, f func()) executor.Timer

	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// AfterFunc holds details about calls to the AfterFunc method.
		AfterFunc []struct {
			// D is the d argument value.
			D time.Duration
			// F is the f argument value.
			F func()
		}
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockAfterFunc sync.RWMutex
	lockNow       sync.RWMutex
}

// AfterFunc calls AfterFuncFunc.
func (mock *ClockMock) AfterFunc(d time.Duration, f func()) executor.Timer {
	if mock.AfterFuncFunc == nil {
		panic("ClockMock.AfterFuncFunc: method is nil but Clock.AfterFunc was just called")
	}
	callInfo := struct {
		D time.Duration
		F func()
	}{
		D: d,
		F: f,
	}
	mock.lockAfterFunc.Lock()
	mock.calls.AfterFunc = append(mock.calls.AfterFunc, callInfo)
	mock.lockAfterFunc.Unlock()
	return mock.AfterFuncFunc(d, f)
}

// AfterFuncCalls gets all the calls that were made to AfterFunc.
// Check the length with:
//
//	len(mockedClock.AfterFuncCalls())
func (mock *ClockMock) AfterFuncCalls() []struct {
	D time.Duration
	F func()
} {
	var calls []struct {
		D time.Duration
		F func()
	}
	mock.lockAfterFunc.RLock()
	calls = mock.calls.AfterFunc
	mock.lockAfterFunc.RUnlock()
	return calls
}

// Now calls NowFunc.
func (mock *ClockMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("ClockMock.NowFunc: method is nil but Clock.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedClock.NowCalls())
func (mock *ClockMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}
