// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"os/exec"
	"sync"
)

// CommandRunnerMock is a mock implementation of executor.CommandRunner.
//
//	func TestSomethingThatUsesCommandRunner(t *testing.T) {
//
//		// make and configure a mocked executor.CommandRunner
//		mockedCommandRunner := &CommandRunnerMock{
//			CommandFunc: func(ctx context.Context, name string, args ...string) *exec.Cmd {
//				panic("mock out the Command method")
//			},
//		}
//
//		// use mockedCommandRunner in code that requires executor.CommandRunner
//		// and then make assertions.
//
//	}
type CommandRunnerMock struct {
	// CommandFunc mocks the Command method.
	CommandFunc func(ctx context.Context, name string, args ...string) *exec.Cmd

	// calls tracks calls to the methods.
	calls struct {
		// Command holds details about calls to the Command method.
		Command []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
	}
	lockCommand sync.RWMutex
}

// Command calls CommandFunc.
func (mock *CommandRunnerMock) Command(ctx context.Context, name string, args ...string) *exec.Cmd {
	if mock.CommandFunc == nil {
		panic("CommandRunnerMock.CommandFunc: method is nil but CommandRunner.Command was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Args []string
	}{
		Ctx:  ctx,
		Name: name,
		Args: args,
	}
	mock.lockCommand.Lock()
	mock.calls.Command = append(mock.calls.Command, callInfo)
	mock.lockCommand.Unlock()
	return mock.CommandFunc(ctx, name, args...)
}

// CommandCalls gets all the calls that were made to Command.
// Check the length with:
//
//	len(mockedCommandRunner.CommandCalls())
func (mock *CommandRunnerMock) CommandCalls() []struct {
	Ctx  context.Context
	Name string
	Args []string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Args []string
	}
	mock.lockCommand.RLock()
	calls = mock.calls.Command
	mock.lockCommand.RUnlock()
	return calls
}
