// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revmux/app/executor"
)

// EventSinkMock is a mock implementation of executor.EventSink.
//
//	func TestSomethingThatUsesEventSink(t *testing.T) {
//
//		// make and configure a mocked executor.EventSink
//		mockedEventSink := &EventSinkMock{
//			EmitFunc: func(event executor.Event)  {
//				panic("mock out the Emit method")
//			},
//		}
//
//		// use mockedEventSink in code that requires executor.EventSink
//		// and then make assertions.
//
//	}
type EventSinkMock struct {
	// EmitFunc mocks the Emit method.
	EmitFunc func(event executor.Event)

	// calls tracks calls to the methods.
	calls struct {
		// Emit holds details about calls to the Emit method.
		Emit []struct {
			// Event is the event argument value.
			Event executor.Event
		}
	}
	lockEmit sync.RWMutex
}

// Emit calls EmitFunc.
func (mock *EventSinkMock) Emit(event executor.Event) {
	if mock.EmitFunc == nil {
		panic("EventSinkMock.EmitFunc: method is nil but EventSink.Emit was just called")
	}
	callInfo := struct {
		Event executor.Event
	}{
		Event: event,
	}
	mock.lockEmit.Lock()
	mock.calls.Emit = append(mock.calls.Emit, callInfo)
	mock.lockEmit.Unlock()
	mock.EmitFunc(event)
}

// EmitCalls gets all the calls that were made to Emit.
// Check the length with:
//
//	len(mockedEventSink.EmitCalls())
func (mock *EventSinkMock) EmitCalls() []struct {
	Event executor.Event
} {
	var calls []struct {
		Event executor.Event
	}
	mock.lockEmit.RLock()
	calls = mock.calls.Emit
	mock.lockEmit.RUnlock()
	return calls
}
