// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"time"
)

// TimerMock is a mock implementation of executor.Timer.
//
//	func TestSomethingThatUsesTimer(t *testing.T) {
//
//		// make and configure a mocked executor.Timer
//		mockedTimer := &TimerMock{
//			ResetFunc: func(d time.Duration) bool {
//				panic("mock out the Reset method")
//			},
//			StopFunc: func() bool {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedTimer in code that requires executor.Timer
//		// and then make assertions.
//
//	}
type TimerMock struct {
	// ResetFunc mocks the Reset method.
	ResetFunc func(d time.Duration) bool

	// StopFunc mocks the Stop method.
	StopFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// Reset holds details about calls to the Reset method.
		Reset []struct {
			// D is the d argument value.
			D time.Duration
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockReset sync.RWMutex
	lockStop  sync.RWMutex
}

// Reset calls ResetFunc.
func (mock *TimerMock) Reset(d time.Duration) bool {
	if mock.ResetFunc == nil {
		panic("TimerMock.ResetFunc: method is nil but Timer.Reset was just called")
	}
	callInfo := struct {
		D time.Duration
	}{
		D: d,
	}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	return mock.ResetFunc(d)
}

// ResetCalls gets all the calls that were made to Reset.
// Check the length with:
//
//	len(mockedTimer.ResetCalls())
func (mock *TimerMock) ResetCalls() []struct {
	D time.Duration
} {
	var calls []struct {
		D time.Duration
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *TimerMock) Stop() bool {
	if mock.StopFunc == nil {
		panic("TimerMock.StopFunc: method is nil but Timer.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedTimer.StopCalls())
func (mock *TimerMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
